const addNativeAttributes =(tagName) =>{
    const defaultAttributes = {
        a: {
          href: '#',
          name: '',
          value: '',
          alt: '',
          src: '',
   
        },
        abbr: {},
        address: {},
        area: {
          shape: 'rect',
          coords: '0,0,0,0',
          href: '#',
        },
        article: {},
        aside: {},
        audio: {
          src: '',
          preload: 'auto',
          autoplay: false,
          loop: false,
          muted: false,
          controls: false,
        },
        b: {},
        base: {
          href: '',
          target: '_blank',
        },
        bdi: {},
        bdo: {},
        blockquote: {},
        body: {},
        br: {},
        button: { innerHTML: 'button',},
        canvas: {},
        caption: {},
        cite: {},
        code: {},
        col: {},
        colgroup: {},
        data: {},
        datalist: {},
        dd: {},
        del: {},
        details: {
          open: 'open',
        },
        dfn: {},
        dialog: {},
        div: {},
        dl: {},
        dt: {},
        em: {},
        embed: {},
        fieldset: {},
        figcaption: {},
        figure: {},
        footer: {},
        form: {name: '',
        target: '',
        autoComplete: '',
        enctype: '',
        method: '',
        action: ''},
        h1: {value: 'Heading',
        innerHTML: 'Heading',},
        h2: {},
        h3: {},
        h4: {},
        h5: {},
        h6: {},
        head: {},
        header: {},
        hgroup: {},
        hr: {},
        html: {},
        i: {},
        iframe: {  src: 'https://www.youtube.com/embed/DeQkMK5LME4',
        allow: 'fullscreen',
        fullscreen: 'false'},
        img: {
          src: '/workspace/assets/image.png',
        alt: 'alt_src',
        loading: ''
        },
        input: {
          type: 'text',
        name: '',
        value: '',
        placeholder: 'placeholder',
        disabled: false,
        required: false,
        autoFocus: false,
        autoComplete: ''
        },
        ins: {},
        kbd: {},
        keygen: {},
        label: {
          for: '',
          value: '',
          innerHTML: ''},
        legend: {},
        li: { value: '',
        innerHTML: ''},
        link: {
                href: 'https://example.com',
                target: '_blank'
          },
        main: {},
        map: {},
        mark: {},
        menu: {},
        menuitem: {},
        meta: {},
        meter: {},
        nav: {},
        noscript: {},
        object: {},
        ol: {},
        optgroup: {},
        option: {},
        output: {},
        p: {},
        param: {},
        pre: {},
        progress: {},
        q: {},
        rp: {},
        rt: {},
        ruby: {},
        s: {},
        samp: {},
        script: {},
        section: {},
        select: {name: '',
        multiple: false,
        size: '',
        disabled: false,
        required: false,
        autoFocus: false,
        autoComplete: ''},
        small: {},
        source: {},
        span: {value: 'text',
        innerHTML: 'text',},
        strong: {},
        style: {},
        sub: {},
        summary: {},
        sup: {},
        table: {},
        tbody: {},
        td: {},
        textarea: {
          name: '',
        placeholder: '',
        cols: '',
        rows: '',
        disabled: false,
        autoFocus: false,
        autoComplete: ''
        },
        tfoot: {},
        th: {},
        thead: {},
        time: {},
        title: {},
        tr: {},
        track: {},
        u: {},
        ul: { value: '',
        innerHTML: '',},
        var: {},
        video: {  src: '/workspace/features/video.mp4',
        poster: '/workspace/assets/video.svg',
        controls: false,
        loop: false,
        muted: false,
        autoPlay: false,
        playsInline: false,
        preload: ''},
        wbr: {},
      }
      
  
    return defaultAttributes[tagName.toLowerCase()] || {}
  }
  

  module.exports = { addNativeAttributes }