export const objProperties = {
  'align-content': [
    'center',
    'flex-end',
    'flex-start',
    'inherit',
    'initial',
    'revert',
    'space-around',
    'space-between',
    'stretch',
    'unset'
  ],
  'align-items': [
    'baseline',
    'center',
    'flex-end',
    'flex-start',
    'inherit',
    'initial',
    'revert',
    'stretch',
    'unset'
  ],
  'align-self': [
    'auto',
    'baseline',
    'center',
    'end',
    'flex-end',
    'flex-start',
    'inherit',
    'initial',
    'normal',
    'revert',
    'safe',
    'self-end',
    'self-start',
    'start',
    'stretch',
    'unsafe',
    'unset'
  ],
  all: ['inherit', 'initial', 'revert', 'unset'],
  animation: ['inherit', 'initial', 'revert', 'unset'],
  'animation-delay': ['inherit', 'initial', 'revert', 'unset'],
  'animation-direction': [
    'alternate',
    'alternate-reverse',
    'inherit',
    'initial',
    'normal',
    'reverse',
    'revert',
    'unset'
  ],
  'animation-duration': ['inherit', 'initial', 'revert', 'unset'],
  'animation-fill-mode': [
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Danger)',
    '500 (Danger)',
    '700 (Danger)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    'backwards',
    'both',
    'fowards',
    'inherit',
    'initial',
    'none',
    'revert',
    'unset'
  ],
  'animation-iteration-count': [
    'infinite',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'animation-name': ['inherit', 'initial', 'none', 'revert', 'unset'],
  'animation-play-state': [
    'inherit',
    'initial',
    'paused',
    'revert',
    'running',
    'unset'
  ],
  'animation-timing-function': [
    'cubic-bezier()',
    'ease',
    'ease-in',
    'ease-in-out',
    'ease-out',
    'inherit',
    'initial',
    'linear',
    'revert',
    'step-end',
    'step-start',
    'steps()',
    'unset'
  ],
  'backface-visibility': [
    'hidden',
    'inherit',
    'initial',
    'revert',
    'unset',
    'visible'
  ],
  background: [
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'background-attachment': [
    'fixed',
    'inherit',
    'initial',
    'local',
    'revert',
    'scroll',
    'unset'
  ],
  'background-blend-mode': [
    'color',
    'color-burn',
    'color-dodge',
    'darken',
    'difference',
    'exclusion',
    'hard-light',
    'hue',
    'inherit',
    'initial',
    'lighten',
    'luminosity',
    'multiply',
    'normal',
    'overlay',
    'revert',
    'saturation',
    'screen',
    'soft-light',
    'unset'
  ],
  'background-clip': [
    'border-box',
    'content-box',
    'inherit',
    'initial',
    'padding-box',
    'revert',
    'unset'
  ],
  'background-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'background-image': [
    'image()',
    'inherit',
    'initial',
    'linear-gradient()',
    'radial-gradient()',
    'repeating-linear-gradient()',
    'repeating-radial-gradient()',
    'revert',
    'unset',
    'url()'
  ],
  'background-origin': [
    'border-box',
    'content-box',
    'inherit',
    'initial',
    'padding-box',
    'revert',
    'unset'
  ],
  'background-position': [
    'bottom',
    'center',
    'inherit',
    'initial',
    'left',
    'revert',
    'right',
    'top',
    'unset'
  ],
  'background-repeat': [
    'inherit',
    'initial',
    'no-repeat',
    'repeat',
    'repeat-x',
    'repeat-y',
    'revert',
    'round',
    'space',
    'unset'
  ],
  'background-size': [
    'auto',
    'contain',
    'cover',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  border: ['inherit', 'initial', 'revert', 'unset'],
  'border-collapse': [
    'collapse',
    'inherit',
    'initial',
    'revert',
    'separate',
    'unset'
  ],
  'border-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'border-spacing': ['inherit', 'initial', 'revert', 'unset'],
  'border-style': [
    'dashed',
    'dotted',
    'double',
    'groove',
    'hidden',
    'inherit',
    'initial',
    'inset',
    'none',
    'outset',
    'revert',
    'ridge',
    'solid',
    'unset'
  ],
  'border-bottom': ['inherit', 'initial', 'revert', 'unset'],
  'border-bottom-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'border-bottom-left-radius': [
    'Radius2',
    'Radius4',
    'Radius8',
    'Round',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'border-bottom-right-radius': [
    'Radius2',
    'Radius4',
    'Radius8',
    'Round',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'border-bottom-style': [
    'dashed',
    'dotted',
    'double',
    'groove',
    'hidden',
    'inherit',
    'initial',
    'inset',
    'none',
    'outset',
    'revert',
    'ridge',
    'solid',
    'unset'
  ],
  'border-bottom-width': [
    'inherit',
    'initial',
    'medium',
    'revert',
    'thick',
    'thin',
    'unset'
  ],
  'border-image': ['inherit', 'initial', 'revert', 'unset', 'url()'],
  'border-image-outset': ['inherit', 'initial', 'revert', 'unset'],
  'border-image-slice': ['inherit', 'initial', 'revert', 'unset'],
  'border-image-source': ['inherit', 'initial', 'revert', 'unset'],
  'border-image-repeat': [
    'inherit',
    'initial',
    'repeat',
    'revert',
    'round',
    'space',
    'stretch',
    'unset'
  ],
  'border-image-width': ['auto', 'inherit', 'initial', 'revert', 'unset'],
  'border-left': ['inherit', 'initial', 'revert', 'unset'],
  'border-left-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'border-left-style': [
    'dashed',
    'dotted',
    'double',
    'groove',
    'hidden',
    'inherit',
    'initial',
    'inset',
    'none',
    'outset',
    'revert',
    'ridge',
    'solid',
    'unset'
  ],
  'border-left-width': [
    'inherit',
    'initial',
    'medium',
    'revert',
    'thick',
    'thin',
    'unset'
  ],
  'border-radius': [
    'Radius2',
    'Radius4',
    'Radius8',
    'Round',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'border-right': ['inherit', 'initial', 'revert', 'unset'],
  'border-right-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'border-right-style': [
    'dashed',
    'dotted',
    'double',
    'groove',
    'hidden',
    'inherit',
    'initial',
    'inset',
    'none',
    'outset',
    'revert',
    'ridge',
    'solid',
    'unset'
  ],
  'border-right-width': [
    'inherit',
    'initial',
    'medium',
    'revert',
    'thick',
    'thin',
    'unset'
  ],
  'border-top': ['inherit', 'initial', 'revert', 'unset'],
  'border-top-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'border-top-left-radius': [
    'Radius2',
    'Radius4',
    'Radius8',
    'Round',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'border-top-right-radius': [
    'Radius2',
    'Radius4',
    'Radius8',
    'Round',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'border-top-style': [
    'dashed',
    'dotted',
    'double',
    'groove',
    'hidden',
    'inherit',
    'initial',
    'inset',
    'none',
    'outset',
    'revert',
    'ridge',
    'solid',
    'unset'
  ],
  'border-top-width': [
    'inherit',
    'initial',
    'medium',
    'revert',
    'thick',
    'thin',
    'unset'
  ],
  'box-decoration-break': [
    'clone',
    'inherit',
    'initial',
    'revert',
    'slice',
    'unset'
  ],
  'box-shadow': ['inherit', 'initial', 'none', 'revert', 'unset'],
  'box-sizing': [
    'border-box',
    'content-box',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  bottom: ['auto', 'inherit', 'initial', 'revert', 'unset'],
  'break-after': [
    'always',
    'auto',
    'avoid',
    'avoid-column',
    'avoid-page',
    'avoid-region',
    'column',
    'inherit',
    'initial',
    'left',
    'page',
    'region',
    'revert',
    'right',
    'unset'
  ],
  'break-before': [
    'always',
    'auto',
    'avoid',
    'avoid-column',
    'avoid-page',
    'avoid-region',
    'column',
    'inherit',
    'initial',
    'left',
    'page',
    'region',
    'revert',
    'right',
    'unset'
  ],
  'break-inside': [
    'auto',
    'avoid',
    'avoid-column',
    'avoid-page',
    'avoid-region',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'caption-side': ['bottom', 'inherit', 'initial', 'revert', 'top', 'unset'],
  'caret-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  clear: [
    'both',
    'inherit',
    'initial',
    'left',
    'none',
    'revert',
    'right',
    'unset'
  ],
  clip: ['auto', 'inherit', 'initial', 'revert', 'unset'],
  color: [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  columns: ['inherit', 'initial', 'revert', 'unset'],
  'column-count': ['inherit', 'initial', 'revert', 'unset'],
  'column-fill': [
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Danger)',
    '500 (Danger)',
    '700 (Danger)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    'auto',
    'balance',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'column-gap': [
    'HalfUnit',
    'Unit',
    'OneAndHalfUnits',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'normal',
    'revert',
    'unset'
  ],
  'column-rule': ['inherit', 'initial', 'revert', 'unset'],
  'column-rule-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'column-rule-style': [
    'dashed',
    'dotted',
    'double',
    'groove',
    'hidden',
    'inherit',
    'initial',
    'inset',
    'none',
    'outset',
    'revert',
    'ridge',
    'solid',
    'unset'
  ],
  'column-rule-width': [
    'XSmall',
    'Small',
    'Medium',
    'Large',
    'XLarge',
    'XXLarge',
    'MaxWidth',
    'inherit',
    'initial',
    'medium',
    'revert',
    'thick',
    'thin',
    'unset'
  ],
  'column-width': [
    'XSmall',
    'Small',
    'Medium',
    'Large',
    'XXLarge',
    'XLarge',
    'MaxWidth',
    'auto',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  content: [
    'attr()',
    'close-quote',
    'inherit',
    'initial',
    'no-close-quote',
    'no-open-quote',
    'none',
    'normal',
    'open-quote',
    'revert',
    'unset'
  ],
  'counter-increment': ['inherit', 'initial', 'none', 'revert', 'unset'],
  'counter-reset': ['inherit', 'initial', 'none', 'revert', 'unset'],
  cursor: [
    'alias',
    'all-scroll',
    'auto',
    'cell',
    'col-resize',
    'context-menu',
    'copy',
    'crosshair',
    'default',
    'e-resize',
    'ew-resize',
    'grab',
    'grabbing',
    'help',
    'inherit',
    'initial',
    'move',
    'n-resize',
    'ne-resize',
    'nesw-resize',
    'no-drop',
    'none',
    'not-allowed',
    'ns-resize',
    'nw-resize',
    'nswe-resize',
    'pointer',
    'progress',
    'revert',
    'row-resize',
    's-resize',
    'se-resize',
    'sw-resize',
    'text',
    'unset',
    'vertical-text',
    'w-resize',
    'wait',
    'zoom-in',
    'zoom-out'
  ],
  direction: ['inherit', 'initial', 'ltr', 'revert', 'rtl', 'unset'],
  display: [
    'block',
    'contents',
    'flex',
    'flow-root',
    'grid',
    'inherit',
    'initial',
    'inline',
    'inline-block',
    'inline-flex',
    'inline-grid',
    'inline-table',
    'list-item',
    'none',
    'revert',
    'run-in',
    'subgrid',
    'table',
    'table-caption',
    'table-cell',
    'table-column',
    'table-column-group',
    'table-footer-group',
    'table-header-group',
    'table-row',
    'table-row-group',
    'unset'
  ],
  'empty-cells': ['hide', 'inherit', 'initial', 'revert', 'show', 'unset'],
  fill: [
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Danger)',
    '500 (Danger)',
    '700 (Danger)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  filter: [
    'blur()',
    'brightness',
    'contrast()',
    'custom()',
    'drop-shadow()',
    'grayscale()',
    'hue-rotate()',
    'inherit',
    'initial',
    'invert()',
    'none',
    'opacity()',
    'revert',
    'saturate()',
    'sepia()',
    'unset',
    'url()'
  ],
  flex: ['auto', 'inherit', 'initial', 'none', 'revert', 'unset'],
  'flex-basis': ['auto', 'inherit', 'initial', 'revert', 'unset'],
  'flex-direction': [
    'column',
    'column-reverse',
    'inherit',
    'initial',
    'revert',
    'row',
    'row-reverse',
    'unset'
  ],
  'flex-flow': ['inherit', 'initial', 'revert', 'unset'],
  'flex-grow': ['inherit', 'initial', 'revert', 'unset'],
  'flex-shrink': ['inherit', 'initial', 'revert', 'unset'],
  'flex-wrap': [
    'inherit',
    'initial',
    'nowrap',
    'revert',
    'unset',
    'wrap',
    'wrap-reverse'
  ],
  float: [
    'inherit',
    'initial',
    'inline-end',
    'inline-start',
    'left',
    'none',
    'revert',
    'right',
    'unset'
  ],
  'flow-into': ['inherit', 'initial', 'none', 'revert', 'unset'],
  'flow-from': ['inherit', 'initial', 'none', 'revert', 'unset'],
  font: ['inherit', 'initial', 'revert', 'unset'],
  'font-display': [
    'auto',
    'block',
    'fallback',
    'inherit',
    'initial',
    'optional',
    'revert',
    'swap',
    'unset'
  ],
  'font-family': [
    'auto',
    'cursive',
    'fantasy',
    'inherit',
    'initial',
    'monospace',
    'revert',
    'sans-serif',
    'serif',
    'unset'
  ],
  'font-feature-settings': ['inherit', 'initial', 'normal', 'revert', 'unset'],
  'font-kerning': [
    'auto',
    'inherit',
    'initial',
    'none',
    'normal',
    'revert',
    'unset'
  ],
  'font-language-override': ['inherit', 'initial', 'normal', 'revert', 'unset'],
  'font-size': [
    'inherit',
    'initial',
    'large',
    'larger',
    'medium',
    'revert',
    'unset',
    'x-large',
    'x-small',
    'xx-large',
    'xx-small',
    'xxx-large'
  ],
  'font-size-adjust': ['auto', 'inherit', 'initial', 'none', 'revert', 'unset'],
  'font-stretch': [
    'condensed',
    'expanded',
    'extra-condensed',
    'exra-expanded',
    'inherit',
    'initial',
    'normal',
    'revert',
    'semi-condensed',
    'semi-expanded',
    'ultra-condensed',
    'ultra-expanded',
    'unset'
  ],
  'font-style': [
    'inherit',
    'initial',
    'italic',
    'normal',
    'olique',
    'revert',
    'unset'
  ],
  'font-synthesis': [
    'inherit',
    'initial',
    'none',
    'revert',
    'style',
    'unset',
    'weight'
  ],
  'font-variant': [
    'inherit',
    'initial',
    'normal',
    'revert',
    'small-caps',
    'unset'
  ],
  'font-variant-alternates': [
    'inherit',
    'initial',
    'normal',
    'revert',
    'unset'
  ],
  'font-variant-caps': [
    'all-petite-caps',
    'all-small-caps',
    'inherit',
    'initial',
    'normal',
    'petite-caps',
    'revert',
    'small-caps',
    'titling-caps',
    'unicase',
    'unset'
  ],
  'font-variant-east-asian': [
    'inherit',
    'initial',
    'normal',
    'revert',
    'unset'
  ],
  'font-variant-ligatures': [
    'inherit',
    'initial',
    'none',
    'normal',
    'revert',
    'unset'
  ],
  'font-variant-numeric': ['inherit', 'initial', 'normal', 'revert', 'unset'],
  'font-variant-position': [
    'inherit',
    'initial',
    'normal',
    'revert',
    'sub',
    'super',
    'unset'
  ],
  'font-weight': [
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900',
    'bold',
    'bolder',
    'inherit',
    'initial',
    'lighter',
    'normal',
    'revert',
    'unset'
  ],
  gap: [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'revert-layer',
    'unset'
  ],
  grid: ['inherit', 'initial', 'revert', 'unset'],
  'grid-area': ['inherit', 'initial', 'revert', 'unset'],
  'grid-auto-columns': ['inherit', 'initial', 'revert', 'unset'],
  'grid-auto-flow': [
    'column',
    'dense',
    'inherit',
    'initial',
    'revert',
    'row',
    'unset'
  ],
  'grid-auto-rows': [
    'column',
    'dense',
    'inherit',
    'initial',
    'revert',
    'row',
    'unset'
  ],
  'grid-column': ['auto', 'inherit', 'initial', 'revert', 'unset'],
  'grid-column-end': ['inherit', 'initial', 'revert', 'unset'],
  'grid-column-gap': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'grid-column-start': ['inherit', 'initial', 'revert', 'unset'],
  'grid-gap': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'grid-row': ['auto', 'inherit', 'initial', 'revert', 'unset'],
  'grid-row-end': ['inherit', 'initial', 'revert', 'unset'],
  'grid-row-start': ['inherit', 'initial', 'revert', 'unset'],
  'grid-row-gap': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'grid-template': ['inherit', 'initial', 'none', 'revert', 'unset'],
  'grid-template-areas': ['inherit', 'initial', 'revert', 'unset'],
  'grid-template-columns': ['auto', 'inherit', 'initial', 'revert', 'unset'],
  'grid-template-rows': ['auto', 'inherit', 'initial', 'revert', 'unset'],
  'hanging-puntuaction': [
    'allow-end',
    'first',
    'force-end',
    'inherit',
    'initial',
    'last',
    'none',
    'revert',
    'unset'
  ],
  height: [
    'XSmall',
    'Small',
    'Medium',
    'Large',
    'XLarge',
    'XXLarge',
    'MaxWidth',
    'auto',
    'fit-content',
    'inherit',
    'initial',
    'max-content',
    'min-content',
    'revert',
    'unset'
  ],
  hyphens: ['auto', 'inherit', 'initial', 'manual', 'none', 'revert', 'unset'],
  'image-orientation': ['inherit', 'initial', 'revert', 'unset'],
  'image-resolution': [
    'from-image',
    'inherit',
    'initial',
    'revert',
    'snap',
    'unset'
  ],
  isolation: ['auto', 'inherit', 'initial', 'isolate', 'revert', 'unset'],
  'justify-content': [
    'center',
    'flex-end',
    'flex-start',
    'inherit',
    'initial',
    'revert',
    'space-around',
    'space-between',
    'unset'
  ],
  'justify-items': [
    'auto',
    'baseline',
    'center',
    'end',
    'first',
    'flex-end',
    'flex-start',
    'inherit',
    'initial',
    'last',
    'left',
    'normal',
    'revert',
    'right',
    'safe',
    'self-end',
    'self-start',
    'start',
    'stretch',
    'unsafe',
    'unset'
  ],
  'justify-self': [
    'auto',
    'baseline',
    'center',
    'end',
    'first',
    'flex-end',
    'flex-start',
    'inherit',
    'initial',
    'last',
    'left',
    'normal',
    'revert',
    'right',
    'safe',
    'self-end',
    'self-start',
    'start',
    'stretch',
    'unsafe',
    'unset'
  ],
  left: ['auto', 'inherit', 'initial', 'revert', 'unset'],
  'letter-spacing': ['inherit', 'initial', 'normal', 'revert', 'unset'],
  'line-height': [
    'XSmall',
    'Small',
    'Medium',
    'Large',
    'XLarge',
    'XXLarge',
    'MaxWidth',
    'inherit',
    'initial',
    'normal',
    'revert',
    'unset'
  ],
  'list-style': [
    'armenian',
    'circle',
    'decimal',
    'decimal-leading-zero',
    'disc',
    'georgian',
    'inherit',
    'initial',
    'lower-alpha',
    'lower-greek',
    'lower-latin',
    'lower-roman',
    'none',
    'outside',
    'revert',
    'square',
    'unset',
    'upper-alpha',
    'upper-latin',
    'upper-roman',
    'url()'
  ],
  'list-style-image': [
    'inherit',
    'initial',
    'none',
    'revert',
    'unset',
    'url()'
  ],
  'list-style-position': [
    'inherit',
    'initial',
    'inside',
    'outside',
    'revert',
    'unset'
  ],
  'list-style-type': [
    'armenian',
    'circle',
    'decimal',
    'decimal-leading-zero',
    'disc',
    'georgian',
    'inherit',
    'initial',
    'lower-alpha',
    'lower-greek',
    'lower-latin',
    'lower-roman',
    'none',
    'revert',
    'square',
    'unset',
    'upper-alpha',
    'upper-latin',
    'upper-roman'
  ],
  margin: [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'auto',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'margin-bottom': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'auto',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'margin-left': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'auto',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'margin-right': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'auto',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'margin-top': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'auto',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'max-height': [
    'XSmall',
    'Small',
    'Medium',
    'Large',
    'XLarge',
    'XXLarge',
    'MaxWidth',
    'inherit',
    'initial',
    'none',
    'revert',
    'unset'
  ],
  'max-width': [
    'XSmall',
    'Small',
    'Medium',
    'Large',
    'XLarge',
    'XXLarge',
    'MaxWidth',
    'inherit',
    'initial',
    'none',
    'revert',
    'unset'
  ],
  'min-height': [
    'XSmall',
    'Small',
    'Medium',
    'Large',
    'XLarge',
    'XXLarge',
    'MaxWidth',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'min-width': [
    'XSmall',
    'Small',
    'Medium',
    'Large',
    'XLarge',
    'XXLarge',
    'MaxWidth',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'mix-blend-mode': [
    'color',
    'color-burn',
    'color-dodge',
    'darken',
    'difference',
    'exclusion',
    'hard-light',
    'hue',
    'inherit',
    'initial',
    'lighten',
    'luminosity',
    'multiply',
    'normal',
    'overlay',
    'revert',
    'saturation',
    'screen',
    'soft-light',
    'unset'
  ],
  'object-fit': [
    'contain',
    'cover',
    'fill',
    'inherit',
    'initial',
    'none',
    'revert',
    'scale-down',
    'unset'
  ],
  'object-position': [
    'bottom',
    'center',
    'inherit',
    'initial',
    'left',
    'revert',
    'right',
    'top',
    'unset'
  ],
  opacity: ['inherit', 'initial', 'revert', 'unset'],
  order: ['inherit', 'initial', 'revert', 'unset'],
  orphans: ['inherit', 'initial', 'revert', 'unset'],
  outline: ['inherit', 'initial', 'revert', 'unset'],
  'outline-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'outline-offset': ['inherit', 'initial', 'revert', 'unset'],
  'outline-style': [
    'dashed',
    'dotted',
    'double',
    'groove',
    'hidden',
    'inherit',
    'initial',
    'inset',
    'none',
    'outset',
    'revert',
    'ridge',
    'solid',
    'unset'
  ],
  'outline-width': [
    'XSmall',
    'Small',
    'Medium',
    'Large',
    'XLarge',
    'XXLarge',
    'MaxWidth',
    'inherit',
    'initial',
    'medium',
    'revert',
    'thick',
    'thin',
    'unset'
  ],
  overflow: [
    'auto',
    'hidden',
    'inherit',
    'initial',
    'revert',
    'scroll',
    'unset',
    'visible'
  ],
  'overflow-x': [
    'auto',
    'hidden',
    'inherit',
    'initial',
    'revert',
    'scroll',
    'unset',
    'visible'
  ],
  'overflow-y': [
    'auto',
    'hidden',
    'inherit',
    'initial',
    'revert',
    'scroll',
    'unset',
    'visible'
  ],
  'overflow-wrap': [
    'anywhere',
    'break-word',
    'inherit',
    'initial',
    'normal',
    'revert',
    'unset'
  ],
  padding: [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'padding-bottom': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'padding-left': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'padding-right': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'padding-top': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'page-break-after': [
    'always',
    'auto',
    'avoid',
    'inherit',
    'initial',
    'left',
    'revert',
    'right',
    'unset'
  ],
  'page-break-before': [
    'always',
    'auto',
    'avoid',
    'inherit',
    'initial',
    'left',
    'revert',
    'right',
    'unset'
  ],
  'page-break-inside': [
    'auto',
    'avoid',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  perspective: ['inherit', 'initial', 'none', 'revert', 'unset'],
  'perspective-origin': [
    'bottom',
    'center',
    'inherit',
    'initial',
    'left',
    'revert',
    'right',
    'top',
    'unset'
  ],
  'pointer-events': [
    'all',
    'auto',
    'fill',
    'inherit',
    'initial',
    'none',
    'painted',
    'revert',
    'stroke',
    'unset',
    'visible',
    'visibleFill',
    'visiblePainted',
    'visibleStroke'
  ],
  position: [
    'absolute',
    'fixed',
    'inherit',
    'initial',
    'relative',
    'revert',
    'static',
    'sticky',
    'unset'
  ],
  quotes: ['inherit', 'initial', 'none', 'revert', 'unset'],
  'region-break-after': [
    'always',
    'auto',
    'avoid',
    'avoid-column',
    'avoid-page',
    'avoid -region',
    'column',
    'inherit',
    'initial',
    'left',
    'page',
    'region',
    'revert',
    'right'
  ],
  'region-break-before': [
    'always',
    'auto',
    'avoid',
    'avoid-column',
    'avoid-page',
    'avoid -region',
    'column',
    'inherit',
    'initial',
    'left',
    'page',
    'region',
    'revert',
    'right',
    'unset'
  ],
  'region-break-inside': [
    'auto',
    'avoid',
    'avoid-column',
    'avoid-page',
    'avoid-region',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'region-fragment': ['auto', 'break', 'inherit', 'initial', 'revert', 'unset'],
  resize: [
    'both',
    'horizontal',
    'inherit',
    'initial',
    'none',
    'revert',
    'unset',
    'vertical'
  ],
  right: ['auto', 'inherit', 'initial', 'revert', 'unset'],
  'scroll-behavior': [
    'auto',
    'inherit',
    'initial',
    'revert',
    'smooth',
    'unset'
  ],
  'scroll-snap-type': [
    'block',
    'both',
    'inherit',
    'initial',
    'inline',
    'mandatory',
    'none',
    'proximity',
    'revert',
    'unset',
    'x',
    'y'
  ],
  src: ['inherit', 'initial', 'revert', 'unset', 'url()'],
  'shape-image-threshold': ['inherit', 'initial', 'revert', 'unset'],
  'shape-inside': [
    'auto',
    'circle()',
    'ellipse()',
    'inherit',
    'initial',
    'outside-shape',
    'polygon()',
    'rectangle()',
    'revert',
    'unset'
  ],
  'shape-margin': [
    'HalfUnit',
    'OneAndHalfUnits',
    'Unit',
    'TwoUnits',
    'ThreeUnits',
    'FourUnits',
    'FiveUnits',
    'SixUnits',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'shape-outside': [
    'border-box',
    'circle()',
    'context-box',
    'ellipse()',
    'image()',
    'inherit',
    'initial',
    'inset()',
    'linear-gradient()',
    'margin-box',
    'none',
    'padding-box',
    'polygon()',
    'radial-gradient()',
    'repeating-linear-gradient()',
    'repeating-radial-gradient()',
    'revert',
    'unset',
    'url()'
  ],
  'tab-size': ['inherit', 'initial', 'revert', 'unset'],
  'table-layout': ['auto', 'fixed', 'inherit', 'initial', 'revert', 'unset'],
  'text-align': [
    'center',
    'end',
    'inherit',
    'initial',
    'justify',
    'justify-all',
    'left',
    'match-parent',
    'revert',
    'right',
    'start',
    'unset'
  ],
  'text-align-last': [
    'center',
    'inherit',
    'initial',
    'justify',
    'left',
    'revert',
    'right',
    'unset'
  ],
  'text-decoration': [
    'inherit',
    'initial',
    'line-through',
    'none',
    'overline',
    'revert',
    'underline',
    'unset'
  ],
  'text-decoration-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'text-decoration-line': [
    'inherit',
    'initial',
    'line-through',
    'none',
    'overline',
    'revert',
    'underline',
    'unset'
  ],
  'text-decoration-skip': [
    'edges',
    'inherit',
    'initial',
    'ink',
    'none',
    'objects',
    'revert',
    'spaces',
    'unset'
  ],
  'text-decoration-style': [
    'dashed',
    'dotted',
    'double',
    'inherit',
    'initial',
    'revert',
    'solid',
    'unset',
    'wavy'
  ],
  'text-emphasis': ['inherit', 'initial', 'revert', 'unset'],
  'text-emphasis-color': [
    '300 (danger)',
    '500 (danger)',
    '700 (danger)',
    'Black (Gray)',
    '500 (Gray)',
    '700 (Gray)',
    '900 (Gray)',
    'White (Gray)',
    '100 (Primary)',
    '300 (Primary)',
    '500 (Primary)',
    '700 (Primary)',
    '300 (Success)',
    '500 (Success)',
    '700 (Success)',
    'aliceblue',
    'antiquewhite',
    'Aqua',
    'Aquamarine',
    'Azure',
    'Beige',
    'Bisque',
    'Black',
    'BlanchedAlmond',
    'Blue',
    'BlueViolet',
    'Brown',
    'BurlyWood',
    'CadetBlue',
    'Chartreuse',
    'Chocolate',
    'Coral',
    'CornflowerBlue',
    'Cornsilk',
    'Crimson',
    'Cyan',
    'DarkBlue',
    'DarkCyan',
    'DarkGoldenRod',
    'DarkGray',
    'DarkGrey',
    'DarkGreen',
    'DarkKhaki',
    'DarkMagenta',
    'DarkOliveGreen',
    'DarkOrange',
    'DarkOrchid',
    'DarkRed',
    'DarkSalmon',
    'DarkSeaGreen',
    'DarkSlateBlue',
    'DarkSlateGray',
    'DarkSlateGrey',
    'DarkTurquoise',
    'DarkViolet',
    'DeepPink',
    'DeepSkyBlue',
    'DimGray',
    'DimGrey',
    'DodgerBlue',
    'FireBrick',
    'FloralWhite',
    'ForestGreen',
    'Fuchsia',
    'Gainsboro',
    'GhostWhite',
    'Gold',
    'GoldenRod',
    'Gray',
    'Grey',
    'Green',
    'GreenYellow',
    'HoneyDew',
    'HotPink',
    'IndianRed',
    'Indigo',
    'inherit',
    'initial',
    'Ivory',
    'Khaki',
    'Lavender',
    'LavenderBlush',
    'LawnGreen',
    'LemonChiffon',
    'LightBlue',
    'LightCoral',
    'LightCyan',
    'LightGoldenRodYellow',
    'LightGray',
    'LightGrey',
    'LightGreen',
    'LightPink',
    'LightSalmon',
    'LightSeaGreen',
    'LightSkyBlue',
    'LightSlateGray',
    'LightSlateGrey',
    'LightSteelBlue',
    'LightYellow',
    'Lime',
    'LimeGreen',
    'Linen',
    'Magenta',
    'Maroon',
    'MediumAquaMarine',
    'MediumBlue',
    'MediumOrchid',
    'MediumPurple',
    'MediumSeaGreen',
    'MediumSlateBlue',
    'MediumSpringGreen',
    'MediumTurquoise',
    'MediumVioletRed',
    'MidnightBlue',
    'MintCream',
    'MistyRose',
    'Moccasin',
    'NavajoWhite',
    'Navy',
    'OldLace',
    'Olive',
    'OliveDrab',
    'Orange',
    'OrangeRed',
    'Orchid',
    'PaleGoldenRod',
    'PaleGreen',
    'PaleTurquoise',
    'PaleVioletRed',
    'PapayaWhip',
    'PeachPuff',
    'Peru',
    'Pink',
    'Plum',
    'PowderBlue',
    'Purple',
    'Red',
    'RosyBrown',
    'RoyalBlue',
    'SaddleBrown',
    'Salmon',
    'SandyBrown',
    'SeaGreen',
    'SeaShell',
    'Sienna',
    'Silver',
    'SkyBlue',
    'SlateBlue',
    'SlateGray',
    'SlateGrey',
    'Snow',
    'SpringGreen',
    'SteelBlue',
    'Tan',
    'Teal',
    'Thistle',
    'Tomato',
    'Turquoise',
    'unset',
    'Violet',
    'Wheat',
    'White',
    'WhiteSmoke',
    'Yellow',
    'YellowGreen'
  ],
  'text-emphasis-position': [
    'above',
    'below',
    'inherit',
    'initial',
    'left',
    'revert',
    'right',
    'unset'
  ],
  'text-emphasis-style': [
    'circle',
    'dot',
    'double-cirle',
    'filled',
    'inherit',
    'initial',
    'none',
    'open',
    'revert',
    'sesame',
    'triangle',
    'unset'
  ],
  'text-indent': ['inherit', 'initial', 'revert', 'unset'],
  'text-justify': [
    'auto',
    'inherit',
    'initial',
    'inter-character',
    'inter-word',
    'none',
    'revert',
    'unset'
  ],
  'text-overflow': [
    'clip',
    'ellipsis',
    'inherit',
    'initial',
    'revert',
    'unset'
  ],
  'text-shadow': ['inherit', 'initial', 'revert', 'unset'],
  'text-rendering': [
    'auto',
    'geometricPrecision',
    'inherit',
    'initial',
    'optimizeLegibility',
    'optimize',
    'revert',
    'unset'
  ],
  'text-transform': [
    'capitalize',
    'full-width',
    'inherit',
    'initial',
    'lowercase',
    'none',
    'revert',
    'unset',
    'uppercase'
  ],
  'text-underline-position': [
    'alphabetic',
    'auto',
    'below',
    'inherit',
    'initial',
    'left',
    'revert',
    'unset'
  ],
  top: ['auto', 'inherit', 'initial', 'revert', 'unset'],
  transform: [
    'inherit',
    'initial',
    'matrix()',
    'matrix3d()',
    'none',
    'perspective()',
    'revert',
    'rotate()',
    'rotate3d()',
    'rotateX',
    'rotateY()',
    'rotateZ()',
    'scale3d()',
    'scaleX()',
    'scaleY()',
    'scaleZ()',
    'skewX()',
    'skewY()',
    'translate()',
    'translate3d()',
    'translateX()',
    'translateY()',
    'translateZ()',
    'unset'
  ],
  'transform-origin': [
    'bottom',
    'center',
    'inherit',
    'initial',
    'left',
    'revert',
    'right',
    'top',
    'unset'
  ],
  'transform-style': [
    'flat',
    'inherit',
    'initial',
    'preserve-3d',
    'revert',
    'unset'
  ],
  transition: ['inherit', 'initial', 'revert', 'unset'],
  'transition-delay': ['inherit', 'initial', 'revert', 'unset'],
  'transition-duration': ['inherit', 'initial', 'revert', 'unset'],
  'transition-property': [
    'all',
    'inherit',
    'initial',
    'none',
    'revert',
    'unset'
  ],
  'transition-timing-function': [
    'cubic-bezier()',
    'ease',
    'ease-in',
    'ease-in-out',
    'ease-out',
    'inherit',
    'initial',
    'linear',
    'revert',
    'step-end',
    'step-start',
    'steps()',
    'unset'
  ],
  'unicode-bidi': [
    'bidi-override',
    'embed',
    'inherit',
    'initial',
    'normal',
    'revert',
    'unset'
  ],
  'unicode-range': ['inherit', 'initial', 'revert', 'unset'],
  'user-select': [
    'all',
    'auto',
    'contain',
    'inherit',
    'initial',
    'none',
    'revert',
    'text',
    'unset'
  ],
  'vertical-align': [
    'baseline',
    'bottom',
    'inherit',
    'initial',
    'middle',
    'revert',
    'sub',
    'super',
    'text-bottom',
    'text-top',
    'top',
    'unset'
  ],
  visibility: [
    'collapse',
    'hidden',
    'inherit',
    'initial',
    'revert',
    'unset',
    'visible'
  ],
  'white-space': [
    'inherit',
    'initial',
    'normal',
    'nowrap',
    'pre',
    'pre-line',
    'pre-wrap',
    'revert',
    'unset'
  ],
  widows: ['inherit', 'initial', 'revert', 'unset'],
  width: [
    'auto',
    'fit-content',
    'inherit',
    'initial',
    'max-content',
    'min-content',
    'revert',
    'unset'
  ],
  'will-change': [
    'auto',
    'contents',
    'inherit',
    'initial',
    'opacity',
    'revert',
    'scroll-position',
    'unset'
  ],
  'word-break': [
    'break-all',
    'inherit',
    'initial',
    'keep-all',
    'normal',
    'revert',
    'unset'
  ],
  'word-spacing': ['inherit', 'initial', 'normal', 'revert', 'unset'],
  'z-index': ['auto', 'inherit', 'initial', 'revert', 'unset']
}
