name: Despliegue test

on:
    push:
        branches:
        - test-workflow-cicd

jobs:
    test-workflow:
        runs-on: [self-hosted, develop-instance-web]
        steps:
            - name: Checkout and set up repository
              uses: actions/checkout@v2
              with:
                    fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '16.19'
            - name: Install dependencies on page
              run:  npm install --legacy-peer-deps --no-audit --no-fund --no-optional 
            - name: Set HOME environment variable
              run: echo "HOME=$HOME" >> $GITHUB_ENV
            - name: restart pm2
              run: pm2 restart all